class Product {
  final String jobName;
  final String description;
  final double price;
  final String sellerName;
  final double rating;
  final String imagePath;

  const Product({
    required this.jobName,
    required this.description,
    required this.price,
    required this.sellerName,
    required this.rating,
    required this.imagePath,
  });

  static const mockData = [
    Product(
      jobName: 'Website Development',
      description: 'Build a responsive website using HTML, CSS, and JavaScript.',
      price: 500.00,
      sellerName: 'John Doe',
      rating: 4.8,
      imagePath: 'assets/images/web_development.webp',
    ),
    Product(
      jobName: 'Graphic Design',
      description: 'Create eye-catching graphics for social media and marketing.',
      price: 150.00,
      sellerName: 'Jane Smith',
      rating: 4.7,
      imagePath: 'assets/images/graphic_design.webp',
    ),
    Product(
      jobName: 'Content Writing',
      description: 'Write SEO-friendly articles and blog posts.',
      price: 100.00,
      sellerName: 'Alice Johnson',
      rating: 4.9,
      imagePath: 'assets/images/content_writing.webp',
    ),
    Product(
      jobName: 'Mobile App Development',
      description: 'Develop a mobile application for Android and iOS platforms.',
      price: 1200.00,
      sellerName: 'David Brown',
      rating: 4.6,
      imagePath: 'assets/images/mobile_app.webp',
    ),
    Product(
      jobName: 'SEO Optimization',
      description: 'Improve website ranking on search engines with SEO techniques.',
      price: 300.00,
      sellerName: 'Emma Davis',
      rating: 4.9,
      imagePath: 'assets/images/seo_optimization.webp',
    ),
    Product(
      jobName: 'Digital Marketing',
      description: 'Manage digital marketing campaigns to boost online presence.',
      price: 450.00,
      sellerName: 'Michael Wilson',
      rating: 4.8,
      imagePath: 'assets/images/digital_marketing.webp',
    ),
    Product(
      jobName: 'Video Editing',
      description: 'Edit and produce high-quality videos for various purposes.',
      price: 200.00,
      sellerName: 'Olivia Miller',
      rating: 4.7,
      imagePath: 'assets/images/video_editing.webp',
    ),
    Product(
      jobName: 'Translation Services',
      description: 'Translate documents and content between multiple languages.',
      price: 80.00,
      sellerName: 'Liam Anderson',
      rating: 4.9,
      imagePath: 'assets/images/translation_services.webp',
    ),
    Product(
      jobName: 'Voice Over',
      description: 'Provide professional voice over services for videos and ads.',
      price: 250.00,
      sellerName: 'Sophia Martinez',
      rating: 4.8,
      imagePath: 'assets/images/voice_over.webp',
    ),
    Product(
      jobName: 'Data Analysis',
      description: 'Analyze data and provide insights for business decisions.',
      price: 600.00,
      sellerName: 'James Rodriguez',
      rating: 4.7,
      imagePath: 'assets/images/data_analysis.webp',
    ),
    Product(
      jobName: 'Social Media Management',
      description: 'Manage social media accounts and grow your online presence.',
      price: 350.00,
      sellerName: 'Emily Harris',
      rating: 4.8,
      imagePath: 'assets/images/social_media_management.webp',
    ),
    Product(
      jobName: 'Email Marketing',
      description: 'Create and manage email marketing campaigns.',
      price: 400.00,
      sellerName: 'Daniel Clark',
      rating: 4.7,
      imagePath: 'assets/images/email_marketing.webp',
    ),
    Product(
      jobName: 'Photography',
      description: 'Professional photography services for events and products.',
      price: 800.00,
      sellerName: 'Sophia Lewis',
      rating: 4.9,
      imagePath: 'assets/images/photography.webp',
    ),
    Product(
      jobName: '3D Modeling',
      description: 'Create 3D models for games, architecture, and products.',
      price: 700.00,
      sellerName: 'William Scott',
      rating: 4.8,
      imagePath: 'assets/images/3d_modeling.webp',
    ),
    Product(
      jobName: 'Legal Consulting',
      description: 'Provide legal advice and consultation for various issues.',
      price: 1000.00,
      sellerName: 'Harper Brown',
      rating: 4.9,
      imagePath: 'assets/images/legal_consulting.webp',
    ),
    Product(
      jobName: 'Virtual Assistant',
      description: 'Provide administrative support remotely.',
      price: 150.00,
      sellerName: 'Mason Martinez',
      rating: 4.6,
      imagePath: 'assets/images/virtual_assistant.webp',
    ),
    Product(
      jobName: 'Web Scraping',
      description: 'Extract data from websites using web scraping techniques.',
      price: 300.00,
      sellerName: 'Isabella Thompson',
      rating: 4.7,
      imagePath: 'assets/images/web_scraping.webp',
    ),
    Product(
      jobName: 'Online Tutoring',
      description: 'Provide online tutoring sessions in various subjects.',
      price: 50.00,
      sellerName: 'Liam White',
      rating: 4.9,
      imagePath: 'assets/images/online_tutoring.webp',
    ),
    Product(
      jobName: 'Accounting Services',
      description: 'Offer accounting and bookkeeping services for businesses.',
      price: 500.00,
      sellerName: 'Ella Robinson',
      rating: 4.8,
      imagePath: 'assets/images/accounting_services.webp',
    ),
    Product(
      jobName: 'Business Consulting',
      description: 'Provide business strategy and management consulting.',
      price: 1200.00,
      sellerName: 'James Walker',
      rating: 4.7,
      imagePath: 'assets/images/business_consulting.webp',
    ),
    Product(
      jobName: 'Animation Services',
      description: 'Create animations for videos, games, and advertisements.',
      price: 900.00,
      sellerName: 'Amelia Harris',
      rating: 4.8,
      imagePath: 'assets/images/animation_services.webp',
    ),
  ];
}
